### ISSUE TITLE
What is x and y in NativeImageCropper.cropRect

### ISSUE THREAD

**Issue by minh-dai** [cosee/native_image_cropper#81]
i am using the camera library to take a photo I get an XFile.
And i want to crop a square with a width equal to 70% and in the center of the image.
i started with topLeftX and topLeftY but when i crop, it returns for me the wrong image. 
Could you expand for me how can i use the function cropRect.

This is my code:

```dart
Future<Uint8List?> cropImage(XFile image) async {
    final imageBytes = await image.readAsBytes();
    final originalImage = await decodeImageFromList(imageBytes);

    final imageHeight = originalImage.height;
    final imageWidth = originalImage.width;
    
    final squareSideLength = (imageWidth * 0.7).toInt();
    final centerX = imageWidth ~/ 2;
    final centerY = imageHeight ~/ 2;

    final topLeftX = centerX - (squareSideLength / 2);
    final topLeftY = centerY - (squareSideLength / 2);

    final bottomLeftX = centerX - (squareSideLength / 2);
    final bottomLeftY = centerY + (squareSideLength / 2);

    final bottomRightX = centerX + (squareSideLength / 2);
    final bottomRightY = centerY + (squareSideLength / 2);

    final topRightX = centerX + (squareSideLength / 2);
    final topRightY = centerY - (squareSideLength / 2);

    final croppedImage = await NativeImageCropper.cropRect(
      x: topLeftX.toInt(),
      y: topLeftY.toInt(),
      width: squareSideLength,
      height: squareSideLength,
      bytes: imageBytes,
    );

    return croppedImage;
  }
```

**Comment by quoc-huynh-cosee** [comment]
Hi @minh-dai,

could you please provide more details about the problem you'd like me to elaborate on? Additionally if you can provide an example of the original image and the expected image, it would help me to understand your problem better.

The only problem I see in your code is that you use `squareSideLength` for both `width` and `height`, which could lead to unexpected results if the original width is greater than the height (probably the plugin should throw an exception for that, I will note it for now).

Here is a simplified example: 
- original image (2000x1000)
- crop image (70% width -> 1400x1400)
- result image (1400x1000), height cannot be greater than the original height

**Comment by DAIHUISENNB** [comment]
@minh-dai It should be that the image automatically rotated, causing the height of the image to not match your y. My solution is:  https://github.com/cosee/native_image_cropper/issues/82

**Comment by quoc-huynh-cosee** [comment]
@minh-dai Can you try out the new version `0.6.0` and check if your issue still remains?
